# Generated by Django 3.2.5 on 2024-01-19 13:17

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_appsettings_heatmap_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="heatmap_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/Users/dmrom/age-friendly/app/static"
                ),
            ),
        ),
    ]
