# Generated by Django 3.2.5 on 2024-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_appsettings_heatmap_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="bad_color",
            field=models.CharField(default="#F57965", max_length=100),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="good_color",
            field=models.CharField(default="#24693D", max_length=100),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="okay_color",
            field=models.CharField(default="#6DB463", max_length=100),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="one_color",
            field=models.CharField(default="#E64E4B", max_length=100),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="zero_color",
            field=models.CharField(default="#A3123A", max_length=100),
        ),
    ]
