# Generated by Django 3.2.5 on 2024-01-19 13:45

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_rename_zero_color_appsettings_empty_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="benches_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/Users/dmrom/age-friendly/app/static"
                ),
            ),
        ),
    ]
