# Generated by Django 3.2.5 on 2024-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240107_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='heatmap_file',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
