# Generated by Django 3.2.5 on 2024-01-19 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_auto_20240119_1432"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appsettings",
            old_name="zero_color",
            new_name="empty_color",
        ),
    ]
