name: Streamlit CI Pipeline

# Run pipeline on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Cache pip dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Run Streamlit app and test if it starts properly
      - name: Start Streamlit app
        run: |
          streamlit run app/app.py &
          sleep 10  # Give the server some time to start

      # Test if Streamlit app is running
      - name: Test Streamlit app
        run: |
          curl -I http://localhost:8501
